from pathlib import Path
import json
import re


PROJECT_ROOT = Path(__file__).resolve().parent.parent

INPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "pdf"
    / "LTM_FY2025-26_parsed.json"
)

OUTPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "normalized"
    / "LTM_FY2025-26_normalized.json"
)


def load_parsed_document():
    """Load the output generated by the PDF parser."""

    with open(
        INPUT_PATH,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(file)


def clean_text(text: str) -> str:
    """
    Basic text normalization.

    We intentionally keep this conservative.
    Financial numbers and page references must not
    be accidentally modified.
    """

    # Normalize Windows line endings
    text = text.replace("\r\n", "\n")

    # Remove excessive spaces
    text = re.sub(r"[ \t]+", " ", text)

    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def normalize_pages(pages):
    """
    Normalize each page while preserving its page number.
    """

    normalized_pages = []

    for page in pages:

        text = clean_text(
            page.get("text", "")
        )

        normalized_pages.append(
            {
                "page": page["page"],
                "text": text,
            }
        )

    return normalized_pages


def build_normalized_document(parsed):
    """
    Convert the parsed PDF into the canonical
    document structure.
    """

    pages = normalize_pages(
        parsed["pages"]
    )

    # Keep page boundaries in the combined content.
    content_parts = []

    for page in pages:

        content_parts.append(
            f"\n--- PAGE {page['page']} ---\n"
        )

        content_parts.append(
            page["text"]
        )

    content = "\n".join(
        content_parts
    )

    normalized = {

        "document_id": parsed["document_id"],

        "company": {
            "name": parsed["company"],
            "former_name": parsed["former_name"],
            "ticker": parsed["ticker"],
        },

        "document_type": parsed[
            "document_type"
        ],

        "title": (
            "LTM Integrated Annual Report "
            "2025-26"
        ),

        "source": {
            "name": parsed["source"],
            "url": None,
        },

        "published_date": None,

        "reporting_period": {
            "label": parsed[
                "reporting_period"
            ],
            "start": "2025-04-01",
            "end": "2026-03-31",
        },

        "content": content,

        "pages": pages,

        # These will be populated in later stages.
        "financial_facts": [],

        "entities": [],

        "relationships": [],

        "metadata": {
            "normalization_version": "1.0",
            "parser": "PyMuPDF",
            "page_count": len(pages),
        },
    }

    return normalized


def save_normalized_document(document):

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        OUTPUT_PATH,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            document,
            file,
            ensure_ascii=False,
            indent=2
        )


def main():

    if not INPUT_PATH.exists():

        raise FileNotFoundError(
            f"Parsed document not found: {INPUT_PATH}"
        )

    print("Loading parsed document...")

    parsed = load_parsed_document()

    print(
        f"Pages found: {len(parsed['pages'])}"
    )

    print("Normalizing...")

    normalized = build_normalized_document(
        parsed
    )

    save_normalized_document(
        normalized
    )

    print()
    print("Normalization complete.")
    print()
    print("Output:")
    print(OUTPUT_PATH)
    print()
    print(
        f"Pages: "
        f"{normalized['metadata']['page_count']}"
    )

    print(
        f"Characters: "
        f"{len(normalized['content'])}"
    )


if __name__ == "__main__":
    main()